### PR TITLE
Removed unnecessary checks 

### PR DESCRIPTION
**Pull request by rupinder10**
The earlier code had a lot of unecessary comparisons. Removed them to instantiate appropriate classes with a one time check.

### CODE REVIEW

**Comment by dpisklov** [comment]
Can't really see the diff due to formatting. Can you reformat using standard java formatting?

**Comment by rupinder10** [comment]
Really I used standard java formatting. Of is the tabs ? I used spaces
instead of tabs. You want me to use tabs ?

**Comment by dpisklov** [comment]
You have 2 spaces instead of 4

**Comment by rupinder10** [comment]
Will do

**Comment by rupinder10** [comment]
Can you check now ? I have checked in the changes with the standard java formatting

**Comment by dpisklov** [comment]
I merged this in, however I'm not sure if you saw the disclaimer - this project is effectively dead and superceded by Chronicle-Core and Chronicle-Bytes project.

**Comment by rupinder10** [comment]
I am aware. We havent been able to move to that as yet because of Java 8
dependencies.

**Pull request merged**
