### PR TITLE
Add a version of MappedStore which can be resized

### PR DESCRIPTION
**Pull request by cdman**
The file-handle is kept open during the resize which means that it will work correcly even on "anonymous" files (files which have been deleted from the filesystem).

Warning! Access the Bytes from before the resize call after resize have been called can have undefined consequences (including a JVM crash) and it's the callers responsibility to ensure that that never happens.

This also disallows opening of zero length files (it seems to fail).

This also supersedes #62.

### CODE REVIEW

**Comment by cdman** [comment]
Please let me know if/when you plan to release it since I'm planning on using it internally :-).

**Comment by peter-lawrey** [comment]
We will review and release this week.

**Comment by cdman** [comment]
Ping?

**Comment by peter-lawrey** [comment]
Hello Attila,
  Sorry we haven't got back to you.  We have been rather busy but we should
be able to look at this this week.

regards,
  Peter.

**Comment by BoundedBuffer** [comment]
JIRA raised - see https://higherfrequencytrading.atlassian.net/browse/JLANG-62 <https://higherfrequencytrading.atlassian.net/browse/JLANG-62>

**Comment by leventov** [comment]
Please resolve conflicts with the previous pull request merged.

Generally LGTM (both open PRs), there a few questions

**Comment by cdman** [comment]
I redid this this as #65 with the comments addressed. Closing this PR since I seem to have foobard something during the rebasing and it shows more differences compared to master than just the changes I did.

**Pull request closed without merging**
