### PR TITLE
Add lock-free methods to read variable length data from absolute offets and optionally observe the length of the read data

### PR DESCRIPTION
**Pull request by cdman**

### CODE REVIEW

**Comment by cdman** [comment]
This is a redo of #64 which hopefully addresses all the raised concerns. High level observations:

* readStopBit is now completely garbage free (as it was before) - no allocation. This comes at the cost of some small code duplication
* the new approach is using a "MutableLong" instead of a listener
* this code may allocate a MutableLong (from a thread pool) on the readUTF* calls where the current implementation doesn't. This is a trade-off to avoid duplicating the readUTF2 method (which is fairly large). In my mind if you're dealing with strings (instead of primitives), you're probably OK with allocating some small additional objects

**Comment by cdman** [comment]
Ping? Any feedback on this?

**Comment by peter-lawrey** [comment]
Hello Attila,
   I am not sure what the benefit of adding the MutableLong is.  There is
quite a bit of extra code, but the benefit is not clear to me.
   The purpose of separating the readStopBit0 from readStopBit is to allow
it to be easily inlined for the common case where the value is 0 <= v <=
127.  Not sure it is work changing the code back unless we can see a
performance benefit (or a lack of a performance benefit)
   If you want to know how much was read, you can check the position()
before and after reading.  This is less explicit but does reduce the number
of public methods and simplify the code for the common case where you don't
need to know this.

Regards, Peter.

**Comment by cdman** [comment]
The scenario I'm having in my head is the following: provide a garbage free way to deserialize an object from a given offset. Lets say that the deserialization code is written like this:

    myObj.setFoo(bytes.readLong(offset));
    myObj.setBar(bytes.readStopBit(offset + Long.BYTES));
    myObj.setFizz(bytes.readLong(offset + ???));

My issue is how to find out the number of bytes consumed by `readStopBit` in a thread-safe manner - ie. in a way that multiple parallel calls to the deserialization method - with different object instances of course - work as expected - (hence my using the methods with `offset` - otherwise I could have just used position as you mentioned). Alternatively I can go with the "allocate a Bytes instance for such read and use the methods without offset" but that seems rather heavy-weight.

**Comment by peter-lawrey** [comment]
Bytes in java-lang is fairly heavy weight, however in Chronicle Bytes is it
much lighter and not much more than a few of longs.
Instead of making your MutableLong thread local, you could do this for the
Bytes.
Note: MultiStoreBytes
<https://github.com/OpenHFT/Java-Lang/blob/master/lang/src/main/java/net/openhft/lang/io/MultiStoreBytes.java>
is designed to wrap and rewrap arbitrary underlying stores.

While this might make some sense in java-lang, I don't image adding this to
Chronicle-Bytes.

**Comment by JerryShea** [comment]
Closing as this project has been superseded

**Pull request closed without merging**
